### ISSUE TITLE
Support stable Rust

### ISSUE THREAD

**Issue by emosenkis** [fschutt/printpdf#11]
Using `#![feature(try_from)]` makes this impossible to use from projects based on stable Rust.

**Comment by fschutt** [comment]
Oh, thanks! I used it for the image loading until #7 happened and removed all traces of `TryFrom` in https://github.com/fschutt/printpdf/commit/a834572d5c0cfb632cbf3da3d95033759ed7f704 - the feature isn't actually used. The library should work on stable, I just forgot to remove the `try_from`.

Thanks for reporting, I'll fix this!

**Comment by fschutt** [comment]
@emosenkis Just in case you are using this library: I've updated the `doc.save()` method to use a `BufWriter` to enforce buffered output - this is a breaking change. Don't use the crate from `crates.io` for now, just use the `{ git = " ... " }` version.

**Comment by emosenkis** [comment]
Thanks. So long as I'm here... Is it possible to draw a circle? I read that
bezier curves can only approximate circles and even that sounds complicated.

**Comment by fschutt** [comment]
@emosenkis No, drawing a circle is not possible in PDF, because PDF doesn't know what a circle is. You can only approximate it:

```rust
    const c: f64 = 0.551915024494; // approximation of circle
    
    let radius = 48.0;         // radius in pt
    
    let offset_x = 100.0;     // where to put the circle on the page
    let offset_y = 100.0;     // in x and y

    let p10 = Point { x: 0.0 * radius, y: 1.0 * radius };
    let p11 = Point { x: c   * radius, y: 1.0 * radius };
    let p12 = Point { x: 1.0 * radius, y: c   * radius };
    let p13 = Point { x: 1.0 * radius, y: 0.0 * radius };
    
    let p20 = Point { x: 1.0 * radius, y: 0.0 * radius };
    let p21 = Point { x: 1.0 * radius, y: -c  * radius };
    let p22 = Point { x: c   * radius, y: -1.0 * radius };
    let p23 = Point { x: 0.0 * radius, y: -1.0 * radius };
    
    let p30 = Point { x: 0.0 * radius, y: -1.0 * radius };
    let p31 = Point { x: -c  * radius, y: -1.0 * radius };
    let p32 = Point { x: -1.0 * radius, y: -c   * radius };
    let p33 = Point { x: -1.0 * radius, y: 0.0 * radius };
    
    let p40 = Point { x: -1.0 * radius, y: 0.0 * radius };
    let p41 = Point { x: -1.0 * radius, y: c * radius };
    let p42 = Point { x: -c * radius, y: 1.0  * radius };
    let p43 = Point { x: 0.0 * radius, y: 1.0 * radius };

    let mut pts  = vec![(p10, true), (p11, true), (p12, true), (p13, true),
                        (p20, true), (p21, true), (p22, true), (p23, true),
                        (p30, true), (p31, true), (p32, true), (p33, true),
                        (p40, true), (p41, true), (p42, true), (p43, true),
    ];

    for p in pts.iter_mut() {
        p.0.x += offset_x;
        p.0.y += offset_y;
    }
    
    let line = Line::new(pts, true, true, true);

    current_layer.add_shape(line);
```

However, while working on this, I discovered a bug related to bezier curve handling. In theory, this should give you a circle, in practice it doesn't. So thanks for your question, I'm working on it.

**Comment by emosenkis** [comment]
Thanks!
