### ISSUE TITLE
Support for using built-in fonts

### ISSUE THREAD

**Issue by emosenkis** [fschutt/printpdf#14]

**Comment by fschutt** [comment]
Yeah, I know. Wasn't a high priority, because technically you can embed fonts plus the support for built-in fonts isn't guaranteed beyond a certain PDF version (I think). I'll take a look.

**Comment by fschutt** [comment]
@emosenkis Fixed in 0.2.0 -  use `add_builtin_font(BuiltinFont::TimesBoldItalic)` for example.
