### ISSUE TITLE
PdfDocument::new without creating a page?

### ISSUE THREAD

**Issue by cakoose** [fschutt/printpdf#24]
What's the reason `PdfDocument::new` also creates the first page.  Is there a way to create an empty document?

I'm writing something that reads in a CSV and creates a document with a page per CSV row.  Things would be a little easier if the first page wasn't automatically created for me.

**Comment by fschutt** [comment]
Becaus PDF readers commonly mark PDFs without pages as "corrupt" PDFs and I wanted to avoid that error directly in the API. That is why the first page is created automatically. I mean, what is the use of a PDF that has no content?

While I can see that it's a problem with generating content, it's more or less just an off-by-one problem, it shouldn't be that hard to fix:

```rust
let csv_rows = [1, 2, 3];
let (current_page, document, _) = PdfDocument::new();

// --

if csv_rows.is_empty() {
    return;
}

row_to_pdf(rows[0], current_page);

for row in rows.iter().skip(1) {
     current_page = document.new_page();
     row_to_pdf(row, current_page);
}
```

Yeah, it doesn't look nice API-wise, but it's better to avoid the common mistake of not creating an initial page and ending up with a corrupt PDF.

**Comment by cakoose** [comment]
I see.  My personal preference is still for the simpler API, but I understand.
