### ISSUE TITLE
Fonts are broken in iOS pdf viewer

### ISSUE THREAD

**Issue by fhars** [fschutt/printpdf#26]
Text using embedded fonts is not displayed correctly in iOS, like that one:
[target_date.pdf](https://github.com/fschutt/printpdf/files/2720886/target_date.pdf)

which looks like this in iOS:

![grafik](https://user-images.githubusercontent.com/198941/50594844-76aa3a80-0e9e-11e9-9b3e-d5d7ec2d543a.png)

when it should look like this:

![grafik](https://user-images.githubusercontent.com/198941/50594913-be30c680-0e9e-11e9-8ecb-f5c53e0347f6.png)

I made it display correctly by a roundtrip through pdf2ps and ps2pdf, which also made the file 20 times smaller.

**Comment by fschutt** [comment]
Well, I'm terribly sorry about that, of course. I did not test it on the iOS PDF viewer - it does view correctly on other PDF viewers, though. Thanks for reporting, I'll look into it.

**Comment by eutampieri** [comment]
The same is for macOS viewer of course, because they share CorePDF. Here's the font and the PDF produced
[test_working.pdf](https://github.com/fschutt/printpdf/files/2759889/test_working.pdf)
[OCRAStd.ttf.zip](https://github.com/fschutt/printpdf/files/2759893/OCRAStd.ttf.zip)
