### ISSUE TITLE
UTF-8 vs PDF built-in fonts

### ISSUE THREAD

**Issue by henriksten65** [fschutt/printpdf#30]
It seems the PDF built-in fonts use the ISO-8859-1 encoding which causes output of a lot of "national" characters look wrong.  Could printpdf be modified to check if the selected font is built-in and then translate the String contents into something that looks right on output?  If the String contains characters not available in ISO-8859-1 they could maybe just be discarded?

The recoding of the String is quite straightforward - if the character code value is less than 256 then use it, otherwise discard it (or replace with NBSP or something else?).

If the chosen built-in font is 'Symbol' or 'Zapf Dingbats' then something more convoluted may have to be done, if at all.

**Comment by fschutt** [comment]
Yeah, I haven't looked into that, mostly because it's a size optimization. Usually it's easier to just embed a proper font. You can also try to use an external tool to do that, i.e. embed your font and then let a PDF-fixing tool such as xpdf or similar process the PDF file again (to reduce the size).

**Comment by robinkrahl** [comment]
`printpdf` should at least provide a method to print ISO-8859-1 encoded bytes.  Currently, it can only print Rust strings, which are always UTF-8 encoded, so it’s impossible to use non-ASCII characters and builtin fonts.

Would you accept a PR that adds a `write_text_builtin` method to `PdfLayerReference` that takes a byte slice and a `Builtin` variant?

**Comment by fschutt** [comment]
Well `write_text` uses a font ID so you can either use a built-in or an external font. Making a separate function for builtin vs external fonts and all the different encodings could duplicate functionality unnecessarily.

Instead it would be better to just make a static function like `check_iso_8859` or `convert_text_to_iso_8859` or something like that. Then the user of the library can decide what to do if the text isn't ISO-conform.
