### ISSUE TITLE
PNG and JPG images support

### ISSUE THREAD

**Issue by XVilka** [fschutt/printpdf#36]
It's annoying to convert the image to BMP beforehand. Would be nice to have the ability to add also PNG and JPG images. What about using [image-rs](https://github.com/image-rs/image) crate for this?

## 2. Supported Image Formats
```image``` provides implementations of common image format encoders and decoders.

### 2.1 Supported Image Formats
| Format | Decoding | Encoding |
| ------ | -------- | -------- |
| PNG    | All supported color types | Same as decoding|
| JPEG   | Baseline and progressive | Baseline JPEG |
| GIF    | Yes | Yes |
| BMP    | Yes | RGB(8), RGBA(8), Gray(8), GrayA(8) |
| ICO    | Yes | Yes |
| TIFF   | Baseline(no fax support) + LZW + PackBits | RGB(8), RGBA(8), Gray(8) |
| Webp   | Lossy(Luma channel only) | No |
| PNM    | PBM, PGM, PPM, standard PAM | Yes |

### 2.2 The ```ImageDecoder``` Trait
All image format decoders implement the ```ImageDecoder``` trait which provides the following methods:
+ **dimensions**: Return a tuple containing the width and height of the image
+ **colortype**: Return the color type of the image.
+ **row_len**: Returns the length in bytes of one decoded row of the image
+ **read_scanline**: Read one row from the image into buf Returns the row index
+ **read_image**: Decode the entire image and return it as a Vector
+ **load_rect**: Decode a specific region of the image

## 3 Pixels
```image``` provides the following pixel types:
+ **Rgb**: RGB pixel
+ **Rgba**: RGBA pixel
+ **Luma**: Grayscale pixel
+ **LumaA**: Grayscale with alpha

**Comment by fschutt** [comment]
Umm... PNG and JPG are already supported? printpdf already uses the image crate. You need to enable the `embedded_images` feature: https://github.com/fschutt/printpdf/blob/620142e74858f0e80462d3eadb799f325478b7c6/Cargo.toml#L27

https://github.com/fschutt/printpdf/blob/620142e74858f0e80462d3eadb799f325478b7c6/Cargo.toml#L17-L21

**Comment by XVilka** [comment]
Ah, ok, then it should be written in the README. Sorry for the confusion.
