### ISSUE TITLE
Character placement sometimes off

### ISSUE THREAD

**Issue by henriksten65** [fschutt/printpdf#40]
Sometimes, when generating PDFs, character placement seems to become broken, or there are extra spaces inserted.  Attached are two images; one showing the expected result and the other the strange result.

The PDFs these images were cut from were generated with the exact same code.  The only thing differing between the generated PDFs should be a serial number high up on the page (which I cropped when converting PDF to JPG).  The string "Godkänd för F-skatt" is a literal string in the code; it was added to the PDF like this (The font used is "LiberationSans-Bold.ttf"):

`current_pdf_layer.use_text("Godkänd för F-skatt".to_string(), 10, Mm(155.0), Mm(56.0), &font_lib_sans_bold);`

For generating JPGs from PDFs I did

`gm convert -crop 595x692+0+150 "$pdf" "$pdf".jpg`

For a test run I generated 800 PDFs and noticed that 716 were looking as expected but the rest were not (and those, in turn, were often differing in different places).

My system is xubuntu 19.10.  All software should be up to date.

![19](https://user-images.githubusercontent.com/17674524/69646556-49dbb480-1068-11ea-898e-79a710c59436.jpg)

![20](https://user-images.githubusercontent.com/17674524/69646571-4fd19580-1068-11ea-87d1-f141dd0b1224.jpg)

**Comment by fschutt** [comment]
Well, this is a very weird issue that seems to be pretty random. Thanks for reporting, but I currently have no clue why this is happening - probably the kerning or spacing information is being generated wrong, but I'm not sure why it's correct 90% of the time.
