### ISSUE TITLE
Links

### ISSUE THREAD

**Issue by lucidBrot** [fschutt/printpdf#42]
Is it possible to use hyperlinks within the pdf? When I use the url directly in the string for `use_text()`, it is clickable, but I would like to display other text that opens the link when clicked.

**Comment by fschutt** [comment]
No, I think that would only be possible with embedded Javascript, which then opens the hyperlink. I'm not aware that PDF viewers themselves support hyperlinks.

**Comment by lucidBrot** [comment]
Alright, thanks for the quick and knowledgeable reply
