### ISSUE TITLE
Divide Mm by Mm not possible?

### ISSUE THREAD

**Issue by tronta** [fschutt/printpdf#48]
I'm trying to calculate how often x fits into y and would expect a float:
let a: f64 = Mm(x) / Mm(y);
But somehow it seems not possible. Is this not implemented?
Is there a workaround?
Or am I doing sth wrong?
I have also problems when multiplying: let b: Mm = Mm(x) * y: f64

**Comment by fschutt** [comment]
Yeah, sorry, you'll have to do it yourself: `Mm(x.0 / y.0)`

**Comment by tronta** [comment]
Thanks a lot. I guessed it already.
I guess this feature would be useful. If I have some time, I might try to implement it...

**Comment by tronta** [comment]
@sapir , Thanks a lot for fixing this issue!
