### ISSUE TITLE
Inserting image doesn't seem to work (on Windows)

### ISSUE THREAD

**Issue by bottiger** [fschutt/printpdf#61]
Hi. I'm trying to generate a pdf and insert an image, but it simply doesn't seem to work. The code is almost just a copy/paste from the documentaion. I do not have a pure linux machine, but I have tested it on windows and the windows subsystem for linux. In both cases the code compiles, runs, reads an image and produces a pdf document - albeit a completely empty one.

I have attached both the image I run the code with all well as the pdf I produce.

[pdf-img.zip](https://github.com/fschutt/printpdf/files/5135995/pdf-img.zip)
[qrcodes.pdf](https://github.com/fschutt/printpdf/files/5135991/qrcodes.pdf)

The code is located in a test and looks like this:

```
    #[tokio::test]
    async fn test_pdf() {
        let mut pdf_source = PathBuf::from(&env!("CARGO_MANIFEST_DIR").to_owned());
        pdf_source.push("out");
        pdf_source.push("codes");
        pdf_source.set_extension("pdf");

        let file = File::create(pdf_source).unwrap();

        log::debug!("Writing pdf to location: {:?}", file);

        let doc = make_pdf();
        let res = save_pdf(doc, file);

        assert!(res.is_ok());
    }

pub fn make_pdf() -> PdfDocumentReference { // qrcodes: Vec<QrCode>
	let (doc, page1, layer1) = PdfDocument::new("PDF_Document_title", Mm(210.0), Mm(297.0), "Layer 1");
    let current_layer = doc.get_page(page1).get_layer(layer1);

	// currently, the only reliable file format is bmp (jpeg works, but not in release mode)
    // this is an issue of the image library, not a fault of printpdf
    
    //let mut image_file = File::open("C:\\Users\\arbo\\Google Drive\\qrgithub\\assets\\pdf-img.bmp").unwrap();
    //let image = Image::try_from(image::bmp::BmpDecoder::new(&mut image_file).unwrap()).unwrap();
    let image_bytes = include_bytes!("/mnt/c/Users/arbo/Google Drive/qrgithub/assets/pdf-img.bmp");
    let mut reader = Cursor::new(image_bytes.as_ref());

    let decoder = BmpDecoder::new(&mut reader).unwrap();
    let image2 = Image::try_from(decoder).unwrap();

    log::debug!("decoded image: {:?}", image2);

    // translate x, translate y, rotate, scale x, scale y
    // by default, an image is optimized to 300 DPI (if scale is None)
    // rotations and translations are always in relation to the lower left corner
    image2.add_to_layer(current_layer, Some(Mm(100.0)), Some(Mm(100.0)), None, None, None, None);

	doc
}

pub fn save_pdf(doc: PdfDocumentReference, file: File) -> Result<(), Error> {
	let res = doc.save(&mut BufWriter::new(file));

	res
}

```

**Comment by fschutt** [comment]
I'm currently not sure why it happens. The generated PDF content stream is correct:

```
/OC /MC0 BDC
q
q
1.0 0.0 0.0 1.0 283.4646 283.4646 cm
120.00001400000002 0.0 0.0 79.920009324 0.0 0.0 cm
/X0 Do
Q
Q
EMC
```

The line `/X0 Do` should show the image, also I've checked that the image (named `X0`) is inserted correctly in the PDF resources:

![image](https://user-images.githubusercontent.com/12084016/91822864-aba0fe80-ec38-11ea-8b5b-eec699861afe.png)

But you're right that it doesn't show an image - not on Windows, not on Linux either.

**Comment by fschutt** [comment]
I understand the problem. Your image has an alpha channel, which is not supported **by PDF**. Alpha channels can only be "mask images" (aka soft masks or "SMasks"). printpdf currently has no SMask support. I can add it, but that would take a few days.

With alpha channels, printpdf falls back to "DeviceN" encoding, which is CMYK - it's the wrong format and the PDF viewer probably simply aborts because it's the wrong image type (it should be "DeviceRGB" + one SMask "DeviceGray" to encode the alpha channel separately).

Once you remove the alpha channel from your image, it works.

**Comment by bottiger** [comment]
@fschutt Thanks for getting back to me. Nice to know! I actually don't need alpha channels at all, so that should not be a problem. I just picked a random image of the internet in order to see if I could get something to work - which I could not.

I will try it out again whenever I get the time. Maybe today, maybe tomorrow :)

**Comment by bottiger** [comment]
@fschutt I don't think the alpha channel is the entire story. I have tried a few different bmp images, and none of them worked with the code above.
I also tried to convert one of them to a jpg (which doesn't support transparency) and the back to bmp. Still without any luck.

**Comment by fschutt** [comment]
Well, you can send me more images to test - but for your image in the original post it was because of the alpha channel. Once I removed the alpha channel, everything worked.

**Comment by bottiger** [comment]
@fschutt I'm sorry. I was just about to submit a bunch of images which didn't work either. However, then I realized that I was testing with some code where the "insert image" part was commented out. 

You are correct that it seems to work.

have a nice day :)
