### ISSUE TITLE
PdfDocumentReference::add_builtin_font returns a Result but cannot fail

### ISSUE THREAD

**Issue by robinkrahl** [fschutt/printpdf#66]
The `add_builtin_font` method of the `PdfDocumentReference` struct returns a `Result` but as far as I see, it cannot fail.  Would you accept a PR that refactors the method and removes the `Result`?

**Comment by fschutt** [comment]
It's mostly for consistency, so that `add_builtin_font()` and `add_external_font()` have the same API definition. It's on purpose.

**Comment by robinkrahl** [comment]
Ah, okay.  Thanks for the explanation.
