### ISSUE TITLE
Handling untrusted user input

### ISSUE THREAD

**Issue by robinkrahl** [fschutt/printpdf#69]
When writing untrusted user input to a PDF file with `write_text`, are there any security implications?  Should the user escape or remove some control characters, or will all characters be interpreted as a string?

**Comment by fschutt** [comment]
I think that depends on the PDF viewer, but generally it's just a string. Non-conforming characters will be converted to WinAnsiEncoding, so they'll just show up as garbage like `Hâ€™llo world`

**Comment by robinkrahl** [comment]
Great, thank you!
