### ISSUE TITLE
Use rust life times instead of Rc<>

### ISSUE THREAD

**Issue by fd** [fschutt/printpdf#81]
@fschutt Are you okay If I attempt to refactor the library such that `PageRef` and `LayerRef` types actually use rust life times instead of `Rc<>`? This would obviously be a breaking change but I believe it would more accurately communicate mutability and ownership of the referenced data.

**Comment by fschutt** [comment]
You can do it, but it would likely be a waste of time, see https://github.com/fschutt/printpdf/issues/73#issuecomment-712794370

I'll refactor the API properly in the next version anyway, so the `PageRef` and `LayerRef` classes will be removed.

**Comment by fd** [comment]
Yeah I saw you wanted to do a rewrite in a few years (aka. not today). My immediate goals are:

* removing the `Pdf{Document,Page,Layer}Reference` types and have the api use regular references
* model the XObject references API more like PDF. (eg: add XObject to doc and get XObjectRef, Add XObjectRef to page and get resource name, use resource name to render image). This would allow image stream deduplication and soft masks to be implemented.

These changes could be a stepping stone to a more convenient v2 API.

**Comment by fschutt** [comment]
ok, go ahead if you want

**Comment by fschutt** [comment]
`PageRef` and `LayerRef` are removed in the `0.8` version, for a more simplified API (layers are now just operation with `BeginLayer { id }` and `EndLayer { id }` in the Page `/Content` stream.

i.e.

```rust
let mut doc = PdfDocument::new("My PDF");
let layer_id = doc.add_layer(Layer { ... });
let page_content = vec![
    Op::BeginLayer { layer_id },
    // layer ops...
    Op::EndLayer { layer_id },
];
let page = Page::new(210.0, 297.0, page_content);
let pdf = doc.with_pages(vec![page]).save_to_bytes();
```
