### ISSUE TITLE
use servo euclid for point

### ISSUE THREAD

**Issue by dzmitry-lahoda** [fschutt/printpdf#83]
https://github.com/fschutt/printpdf/blob/b362afa6caf735e566b52aba0d2b98dbdb0738c5/src/types/plugins/graphics/two_dimensional/point.rs

i have build my own to render some stuff and mapped it to printpdf stuff. but if printpdf will use that out of box could be cool

**Comment by humb1t** [comment]
@dzmitry-lahoda can you rewrite description? What you have build and mappend, what PrintPDF should use OOB?)

**Comment by fschutt** [comment]
No sorry, printpdf should be independent from other crates types as much as possible.
