### ISSUE TITLE
Is there a way to specify the author of the PDF file?

### ISSUE THREAD

**Issue by jwir3** [fschutt/printpdf#95]
I'm wondering if there is a way to specify additional metadata, such as the author of the PDF file, prior to generation.

**Comment by fschutt** [comment]
You would have to set that in the `DocumentInfo` dictionary: https://github.com/fschutt/printpdf/blob/097defa25d5d5a14520498043a30979fe4af8bba/src/types/plugins/misc/document_info.rs#L17-L24

... but that's not currently exposed in printpdf. It's not that hard to implement, but I have a lot to do myself right now
